// Regenerates the auth background assets from the full-resolution masters.
//
//   node scripts/gen-auth-bg.mjs [sourceDir]
//
// Writes downscaled webp into public/img (served directly, no image optimizer)
// and the inlined blur previews into src/widgets/RandomAnimePic/placeholders.ts.
//
// The 2048px masters are deliberately not kept in the repository — point the
// script at wherever they live. Because public/img is served with an immutable
// Cache-Control, replacing a picture means giving it a new filename, not
// overwriting an existing one.
import { readdir, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import sharp from "sharp";

// The pane is 50vw x 100vh and the sources are square, so `object-cover` scales
// them to the pane's height: the rendered width equals 100vh. 1280 covers
// viewports up to 1440p at DPR 1.
const WIDTH = 1280;
const QUALITY = 72;

// Upscaled and blurred behind the real picture, so a dozen pixels is plenty.
const PREVIEW_WIDTH = 12;
const PREVIEW_QUALITY = 45;

const sourceDir = resolve(process.argv[2] ?? "../anihive-assets-original");
const outputDir = resolve("public/img");
const previewFile = resolve("src/widgets/RandomAnimePic/placeholders.ts");

const files = (await readdir(sourceDir))
  .filter((name) => /^\d{2}\.webp$/.test(name))
  .sort();

if (files.length === 0) {
  throw new Error(`No NN.webp masters found in ${sourceDir}`);
}

const previews = [];

for (const file of files) {
  const master = sharp(join(sourceDir, file));

  const full = await master
    .clone()
    .resize({ width: WIDTH })
    .webp({ quality: QUALITY })
    .toBuffer();
  await writeFile(join(outputDir, file), full);

  const preview = await master
    .clone()
    .resize({ width: PREVIEW_WIDTH })
    .webp({ quality: PREVIEW_QUALITY })
    .toBuffer();
  previews.push(`data:image/webp;base64,${preview.toString("base64")}`);

  console.log(
    `${file}  ${String(Math.round(full.length / 1024)).padStart(4)} KB  preview ${preview.length} B`,
  );
}

await writeFile(
  previewFile,
  `// Generated by scripts/gen-auth-bg.mjs — do not edit by hand.\n` +
    `// ${PREVIEW_WIDTH}px previews of public/img/NN.webp, inlined into the auth pages so\n` +
    `// the pane is never empty while the real picture is still in flight.\n\n` +
    `export const AUTH_BACKGROUND_PREVIEWS = ${JSON.stringify(previews, null, 2)};\n`,
);

console.log(
  `\n${files.length} images -> ${outputDir}\npreviews -> ${previewFile}`,
);
